### ISSUE TITLE
Fails to compile on Rust 1.86

### ISSUE THREAD

**Issue by danielbank** [newinnovations/PDFium-rs#1]
- error message:
```bash
error[E0277]: the trait bound `*mut fpdf_annotation_t__: std::default::Default` is not satisfied
   --> /Users/danielbank/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pdfium-0.5.9/src/pdfium_sys/pdfium.rs:212:42
    |
212 |         let mut annot: FPDF_ANNOTATION = Default::default();
    |                                          ^^^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `*mut fpdf_annotation_t__`
```
 
- Cargo.toml:

```toml
[package]
edition = "2021"

[dependencies]
pdfium = "0.5.9"
```

- examples/pdfium.rs
```rs
use pdfium::*;
use xaac_tauri_lib::{AppError, AppResult};
use std::path::Path;

/// Test function to verify PDFium is working correctly
pub async fn test_pdfium() -> AppResult<String> {
    // Set custom library location if needed (the new crate handles automatic discovery)
    // For macOS ARM64, try our local library first
    #[cfg(target_os = "macos")]
    #[cfg(target_arch = "aarch64")]
    {
        let lib_path = "./libs/pdfium/macos/arm64/";
        if Path::new(lib_path).exists() {
            set_library_location(lib_path);
        }
    }
    
    // Test basic functionality - just try to access the library
    // The pdfium crate initializes on first use
    match lib() {
        Ok(_) => {
            Ok("PDFium successfully loaded and initialized!".to_string())
        }
        Err(e) => {
            Err(AppError::Other(format!("Failed to initialize PDFium library: {}", e)))
        }
    }
}

/// Extended test that demonstrates document operations
pub async fn test_pdfium_with_document(pdf_path: &str) -> AppResult<String> {
    // Set library location if needed
    #[cfg(target_os = "macos")]
    #[cfg(target_arch = "aarch64")]
    {
        let lib_path = "./libs/pdfium/macos/arm64/";
        if Path::new(lib_path).exists() {
            set_library_location(lib_path);
        }
    }

    // Try to load a document
    let doc = PdfiumDocument::new_from_path(pdf_path, None)
        .map_err(|e| AppError::Other(format!("Failed to load PDF document: {}", e)))?;
    
    let page_count = doc.page_count();
    let mut info = format!("Document loaded successfully!\nPage count: {}\n", page_count);
    
    // Get first page info if available
    if page_count > 0 {
        match doc.page(0) {
            Ok(page) => {
                let width = page.width();
                let height = page.height();
                info.push_str(&format!("First page dimensions: {:.2} x {:.2} points\n", width, height));
            }
            Err(e) => {
                info.push_str(&format!("Could not access first page: {}\n", e));
            }
        }
    }
    
    Ok(info)
}

#[tokio::main]
async fn main() -> AppResult<()> {
    println!("Testing PDFium integration...");

    match test_pdfium().await {
        Ok(message) => {
            println!("✅ {}", message);
            
            // If we have a test PDF, try the extended test
            let test_pdf = "examples/test_files/w2.pdf";
            if Path::new(test_pdf).exists() {
                println!("\nTesting with document operations...");
                match test_pdfium_with_document(test_pdf).await {
                    Ok(doc_info) => {
                        println!("✅ {}", doc_info);
                    }
                    Err(e) => {
                        println!("⚠️  Document test failed: {}", e);
                    }
                }
            } else {
                println!("ℹ️  No test PDF found at '{}', skipping document test", test_pdf);
            }
            
            Ok(())
        }
        Err(e) => {
            eprintln!("❌ PDFium test failed: {}", e);
            Err(e)
        }
    }
}
```

**Comment by newinnovations** [comment]
I tried your example, and it seems AI gave you code that does not compile.

What I had to change:
- `try_lib()` instead of `lib()`
- `page.boundaries().media()` to obtain `width` and `height`
- replaced the `AppError` and `AppResult` as I do not have the source for them
- removed the second `set_library_location` which is not needed
- added `tokio` dependency

**Cargo.toml**
```toml
[package]
edition = "2021"

[dependencies]
pdfium = "0.5.9"
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
```

**examples/pdfium.rs**
```rust
use std::path::Path;

use pdfium::*;

/// Test function to verify PDFium is working correctly
pub async fn test_pdfium() -> PdfiumResult<String> {
    // Set custom library location if needed (the new crate handles automatic discovery)
    // For macOS ARM64, try our local library first
    #[cfg(target_os = "macos")]
    #[cfg(target_arch = "aarch64")]
    {
        let lib_path = "./libs/pdfium/macos/arm64/";
        if Path::new(lib_path).exists() {
            set_library_location(lib_path);
        }
    }

    // Test basic functionality - just try to access the library
    // The pdfium crate initializes on first use
    match try_lib() {
        Ok(_) => Ok("PDFium successfully loaded and initialized!".to_string()),
        Err(e) => Err(PdfiumError::LibraryError(format!(
            "Failed to initialize PDFium library: {}",
            e
        ))),
    }
}

/// Extended test that demonstrates document operations
pub async fn test_pdfium_with_document(pdf_path: &str) -> PdfiumResult<String> {
    // Try to load a document
    let doc = PdfiumDocument::new_from_path(pdf_path, None)
        .map_err(|e| PdfiumError::LibraryError(format!("Failed to load PDF document: {}", e)))?;

    let page_count = doc.page_count();
    let mut info = format!(
        "Document loaded successfully!\nPage count: {}\n",
        page_count
    );

    // Get first page info if available
    if page_count > 0 {
        match doc.page(0) {
            Ok(page) => {
                let width = page.boundaries().media()?.width();
                let height = page.boundaries().media()?.height();
                info.push_str(&format!(
                    "First page dimensions: {:.2} x {:.2} points\n",
                    width, height
                ));
            }
            Err(e) => {
                info.push_str(&format!("Could not access first page: {}\n", e));
            }
        }
    }

    Ok(info)
}

#[tokio::main]
async fn main() -> PdfiumResult<()> {
    println!("Testing PDFium integration...");

    match test_pdfium().await {
        Ok(message) => {
            println!("✅ {}", message);

            // If we have a test PDF, try the extended test
            let test_pdf = "examples/test_files/w2.pdf";
            if Path::new(test_pdf).exists() {
                println!("\nTesting with document operations...");
                match test_pdfium_with_document(test_pdf).await {
                    Ok(doc_info) => {
                        println!("✅ {}", doc_info);
                    }
                    Err(e) => {
                        println!("⚠️  Document test failed: {}", e);
                    }
                }
            } else {
                println!(
                    "ℹ️  No test PDF found at '{}', skipping document test",
                    test_pdf
                );
            }

            Ok(())
        }
        Err(e) => {
            eprintln!("❌ PDFium test failed: {}", e);
            Err(e)
        }
    }
}
```

**Output**
```text
Testing PDFium integration...
✅ PDFium successfully loaded and initialized!

Testing with document operations...
✅ Document loaded successfully!
Page count: 2
First page dimensions: 594.96 x 841.92 points
```

Can you test the modified example on your system?

**Comment by danielbank** [comment]
I changed my Cargo.toml to match your suggestion and copy-pasted the entire example code block.  

I am getting the error while compiling pdfium:
```bash
   Compiling pdfium v0.5.9
error[E0277]: the trait bound `*mut fpdf_annotation_t__: std::default::Default` is not satisfied
   --> /Users/danielbank/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pdfium-0.5.9/src/pdfium_sys/pdfium.rs:212:42
    |
212 |         let mut annot: FPDF_ANNOTATION = Default::default();
    |                                          ^^^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `*mut fpdf_annotation_t__`

   Compiling ureq v2.12.1
   Compiling assert-json-diff v2.0.2
   Compiling serial_test_derive v3.2.0
   Compiling downcast v0.11.0
   Compiling fragile v2.0.1
   Compiling wiremock v0.6.4
   Compiling serial_test v3.2.0
   Compiling tokio-test v0.4.4
   Compiling lopdf v0.36.0
   Compiling mockall v0.13.1
For more information about this error, try `rustc --explain E0277`.
error: could not compile `pdfium` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by newinnovations** [comment]
Can you do `rustc -V -v` and post the output?

**Comment by danielbank** [comment]
❯ rustc -V -v
rustc 1.86.0 (05f9846f8 2025-03-31)
binary: rustc
commit-hash: 05f9846f893b09a1be1fc8560e33fc3c815cfecb
commit-date: 2025-03-31
host: aarch64-apple-darwin
release: 1.86.0
LLVM version: 19.1.7

**Comment by danielbank** [comment]
Thanks for pointing that out, when I did `rustup update`, the error resolved.  Feel free to close

**Comment by newinnovations** [comment]
Great. Will update the required rust version to 1.88 in the README.md.
